"""Anti-contamination egress guard for sandbox-verified tasks.

A published fix lives on the package index and the code host, so an agent with
open network egress can fetch the gold patch (and often the hidden test) for the
very repo it is being asked to fix. We saw this empirically: an agent blocked
from the web fell back to `git diff origin/main` (closed by the git-history
scrub in `build_environment_dockerfile`), and when that was closed it ran
`pip download <pkg>==<fixed>` and read the fix straight out of the wheel.

This module ships a per-task `environment/docker-compose.yaml` overlay that
Harbor merges into its compose chain. It blackholes the fix-bearing hosts
(PyPI + GitHub + their CDNs) by mapping them to 0.0.0.0, so `pip download`,
`git fetch github.com`, `curl raw.githubusercontent...` and WebFetch against
those hosts all fail, while general internet (the model API, the agent's own
installer, apt) stays reachable.

This is a *denylist*, which is the realistic control at the docker-compose
layer (`extra_hosts` can add host->ip pins but cannot default-deny). It closes
the obvious, observed leak paths and, crucially, keeps a hosted agent like
claude-code runnable (a full `allow_internet=false` block breaks the agent's
own install + API access). The stricter, more robust form is a default-deny
egress allowlist proxy (allow only the package manager + model API), or a
PyPI mirror frozen to the task's base date so even the index lacks the fix.
See docs/pipelines/README.md and plans/reward_hacking_writeups.md.
"""

from __future__ import annotations

# Hosts that serve the published fix / hidden tests for an open-source repo.
# Blackholed to 0.0.0.0 in the agent's container at run time.
FIX_SOURCE_HOSTS: tuple[str, ...] = (
    "pypi.org",
    "pypi.python.org",
    "files.pythonhosted.org",
    "github.com",
    "api.github.com",
    "raw.githubusercontent.com",
    "codeload.github.com",
    "objects.githubusercontent.com",
)


def git_history_scrub(base_commit: str) -> str:
    """Return Dockerfile RUN lines that strip the repo to `base_commit`.

    The working tree may be reset to the base commit, but `.git` still holds
    the *future*: `origin/main`, tags, the fix commit, and the hidden test. An
    agent can `git diff origin/main HEAD` or `git show origin/main:<testfile>`
    to read the answer with zero network. This is a documented, repeated
    incident on SWE-bench (`git log --all | grep`). We remove the remote,
    delete every ref that points past the base, expire the reflog, and gc so
    the future commits are pruned, while keeping `base_commit` itself reachable
    (the verifier resets test files via `git checkout <base_commit> -- ...`).

    Append these lines AFTER the `git reset --hard <base_commit>` line.
    """
    return (
        f"RUN git checkout -q -B base {base_commit} \\\n"
        f"    && git remote remove origin 2>/dev/null || true\n"
        f"RUN for ref in $(git branch --format='%(refname:short)' | grep -vx base); do "
        f'git branch -D "$ref" 2>/dev/null || true; done \\\n'
        f"    && git tag -l | xargs -r git tag -d >/dev/null 2>&1 || true \\\n"
        f"    && git for-each-ref --format='%(refname)' refs/remotes 2>/dev/null "
        f"| xargs -r -n1 git update-ref -d 2>/dev/null || true \\\n"
        f"    && git reflog expire --expire=now --all 2>/dev/null || true \\\n"
        f"    && git gc --prune=now 2>/dev/null || true\n"
    )


def egress_guard_compose(hosts: tuple[str, ...] = FIX_SOURCE_HOSTS) -> str:
    """Return `environment/docker-compose.yaml` content blackholing `hosts`.

    Harbor includes a task's `environment/docker-compose.yaml` in its compose
    `-f` chain, so the `extra_hosts` entries land on the agent's `main` service.
    """
    lines = [
        "# Auto-generated by Repo2RLEnv: anti-contamination egress guard.",
        "# Blackholes the hosts that serve this repo's published fix and hidden",
        "# tests, so an agent cannot fetch the answer (pip download / git fetch /",
        "# WebFetch against these fail). General internet stays up so the agent",
        "# can install itself and reach its model API. See pipelines/_env_guard.py.",
        "services:",
        "  main:",
        "    extra_hosts:",
    ]
    lines += [f'      - "{h}:0.0.0.0"' for h in hosts]
    return "\n".join(lines) + "\n"
